print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/berni/Develop/github/cube/unity/Assets/Meshes/msh_ground.ma"`)
{		
	file -o "/Users/berni/Develop/github/cube/unity/Assets/Meshes/msh_ground.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/berni/Develop/github/cube/unity/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/berni/Develop/github/cube/unity/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/berni/Develop/github/cube/unity/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
